import Image from "next/image";
import Link from "next/link";
import { TableTabs } from "@/components/TableTabs";
import FeaturedSlider from "@/components/FeaturedSlider";
import LaunchpadSlider from "@/components/LaunchpadSlider";
import MarketMoversSlider from "@/components/MarketMoversSlider";
import TopSalesSlider from "@/components/TopSalesSlider";
import MemecoinsSlider from "@/components/MemecoinsSlider";



export const metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function Home() {


  return (
    <>
    <div>
      <section className="lg:pt-20 pt-24 relative z-20">
        <div className="max-w-[1920px] px-6 mx-auto">
          <h2 className="text-[15px] sm:mb-3 font-semibold text-white leading-normal sm:text-start text-center mb-6">
            Featured
            <span className="bg-text-bg  bg-clip-text text-transparent">
              {" "}
              Collections
            </span>
          </h2>
        <FeaturedSlider/> 
        </div>
        <div className="absolute -bottom-4 right-0 -z-10">
          <img
            src="/images/polygon-1.png"
            alt=""
          />
        </div>
       
      </section>


      <section className="md:pt-4 pt-10 pb-[34px] relative">
        <div className="max-w-[1920px] px-6 mx-auto z-10 relative">
          <div className="w-full flex items-center justify-between">
          <TableTabs/>
          </div>
        </div>
        <div className="lg:h-[653.31px] lg:w-[645.18px]  h-[455px] w-[455px] bg-[#200B07] blur-[200px] absolute -top-[0%] -right-44 z-0"></div>
      
      </section>

      <section className="pt-10 relative">
      <div className="absolute top-0 left-0 max-h-[312px] z-0">
          <img
            className="w-[145px] h-full"
            src="/images/poly-2.png"
            alt=""
          />
        </div>
        <div className="lg:h-[653.31px] h-[455px] w-[455px] lg:w-[645.18px] bg-[#200B07] blur-[200px] absolute -top-[50%] -left-1/3 lg:-left-[302px] z-0"></div>

        <div className="max-w-[1920px] px-6 mx-auto relative z-10">
          <div className="mb-14">
            <h2 className="text-[15px] sm:mb-3 font-semibold text-white leading-normal sm:text-start text-center mb-10">
              Launchpad NFT
              <span className="bg-text-bg  bg-clip-text text-transparent">
                {" "}
                Collections
              </span>
            </h2>
            <LaunchpadSlider/>
          </div>
          <div className="mb-14">
            <h2 className="text-[15px] sm:mb-3 font-semibold text-white leading-normal sm:text-start text-center mb-10">
              NFT Market
              <span className="bg-text-bg  bg-clip-text text-transparent">
                {" "}
                Movers
              </span>
            </h2>
            <MarketMoversSlider/>
          </div>
          <div className="mb-14">
            <h2 className="text-[15px] sm:mb-3 font-semibold text-white leading-normal sm:text-start text-center mb-10">
              Top NFT
              <span className="bg-text-bg  bg-clip-text text-transparent">
                {" "}
                Sales
              </span>
            </h2>
            <TopSalesSlider/>
          </div>
        </div>
        <div className="absolute -top-0 max-h-[312px] -right-2">
          <img
          className="w-auto h-full max-h-[312px]"
            src="/images/poly-3.png"
            alt=""
          />
        </div>



        <div className="absolute -translate-y-1/2 top-3/4 -mt-36 left-0">
          <img
            className="max-h-[312px] bg-contain w-auto"
            src="/images/polygon.png"
            alt=""
          />
        </div>

        <div className="h-[237px] w-[237px] bg-[#200B07] blur-[200px] absolute top-[50%] -left-10 z-0"></div>
        <div className="h-[555px] w-[547px] bg-[#200B07] blur-[200px] absolute -bottom-[0%] -right-44 z-0"></div>


        <div className="absolute -bottom-34 right-0">
          <img
            className="max-h-[312px] bg-contain w-auto"
            src="/images/polygon-11.png"
            alt=""
          />
        </div>

        <div className="hlg:-[600px]  px-5bg-[#1D0B07] blur-[200px] absolute w-1/4 top-1/2 -right-[150px] z-0"></div>
      </section>

      <section className="pt-10 relative">
        <div className="max-w-[1920px] px-6 mx-auto relative z-10">
          <h2 className="text-[15px] sm:mb-3 font-semibold text-white leading-normal sm:text-start text-center mb-6">
            Memecoins on
            <span className="bg-text-bg  bg-clip-text text-transparent">
              {" "}
              Yeehaw
            </span>
          </h2>
          <div className="text-center">
            <h3 className="lg:text-[50px] lg:leading-[75px] mb-10 text-4xl text-white font-semibold">
              Begin your meme adventure with
              <span className="bg-heading-bg  bg-clip-text text-transparent">
                {" "}
                Yeehaw !
              </span>
            </h3>
          </div>
          <MemecoinsSlider/>

          <div className="relative mb-24 mt-[70px]">
            <Image
              width={1340}
              height={402}
            src="/images/banner.png" className="w-full sm:min-h-[250px] min-h-[200px] object-cover h-auto rounded-[16px]" alt="" />
            <div className="absolute top-[22px] left-5 max-w-[150px] w-full">
              <a
                href="#"
                className="text-base transition-all justify-center ease-out duration-500 hover:bg-golden-1100 max-w-[150px] text-center w-full mx-auto font-medium text-white flex items-center rounded-lg bg-golden-1000 border border-golden-1000 p-[7px] px-[14px] gap-2"
              >
                Learn More
              </a>
            </div>
          </div>
        </div>
        <div className="absolute md:block hidden bottom-1/2 -mb-44 left-0 z-0">
        <img
          className="w-auto h-full max-h-[312px]"
            src="/images/poly-6.png"
            alt=""
          /> 
        </div>

        <div className="h-[555px] w-[547px] bg-[#200B07] blur-[200px] absolute -top-[0%] lg:-left-44 -left-[400px] z-0"></div>
        <div className="h-[966px] w-[952px] bg-[#200B07] blur-[200px] absolute -bottom-[0%] lg:-right-[400px] -right-[650px]  z-0"></div>

        <div className="absolute -bottom-20 right-0 z-0">
        <img
          className="w-auto h-full max-h-[312px]"
            src="/images/poly-7.png"
            alt=""
          />
        </div>

      </section>


      </div>

    </>
  );
}

